#!/bin/sh

if [ "$HOSTNAME" == "steffen-ubuntu" ]; then
    alias api='sudo aptitude install'
    alias apud='sudo aptitude update'
    alias apug='sudo aptitude full-upgrade'
    alias aps='aptitude show'
    alias srm='trash-put'
    alias matlabnw='matlab -nojvm -nodisplay -nosplash'
else
    alias trash='gvfs-trash'
    alias rviz='rosrun rviz rviz'
fi

alias resource='source ~/.bashrc'
alias ..='cd ..'
alias em='emacs -nw -q -l ~/git/ubuntu_config/emacs/my_config.el'
alias gemacs='setsid emacs -q -l ~/git/ubuntu_config/emacs/my_config.el'
alias parallel='parallel --gnu'
alias hcat='pygmentize -f terminal256 -O style=native -g'
alias hcat_emacs='hcat ~/git/ubuntu_config/emacs/my_config.el'
alias hcat_bash='hcat ~/git/ubuntu_config/bash/bashrc'

if [ "$HOSTNAME" == "steffen-ubuntu" ]; then
    alias mm='grc -c /usr/share/grc/conf.gcc -e -s make -j 4'
else
    alias mm='grc -c ~/.privat_ubuntu_config/grc/conf.gcc -e -s make -j 8'
    alias mr='grc -c ~/.privat_ubuntu_config/grc/conf.gcc -e -s rosmake --pjobs=8'
    alias cm='grc -c ~/.privat_ubuntu_config/grc/conf.gcc -e -s catkin_make'
fi


alias gitk='git log --graph --decorate'
alias treel='tree -fi'
alias du='du -h --max-depth=0'

alias pdf='evince'
# tar help:
#   c: create
#   x: extract
#   f: file (in/out)
#   z: zip, dezip
alias unpack='tar xf'
alias pack='tar cfz'


# function:
findheader() { find . -type f -name '*.h' | parallel -k "grep -Hn --color=always '$@' "; }
findsource() { find . -type f -name '*.cpp' -o -name '*.hpp' | parallel -k "grep -Hn --color=always '$@' "; }
findcpp() { find . -type f -name '*.cpp' -o -name '*.hpp' -o -name '*.h' | parallel -k "grep -Hn --color=always '$@' "; }

findpy() { find . -type f -name '*.py' | parallel -k "grep -Hn --color=always '$@' "; }

masterUri() { export ROS_MASTER_URI="http://$@:11311"; }
mkcd() { mkdir $@ && cd $@; }
imgs2mjpeg()
{
    ffmpeg -f image2 -i $1 -c:v libx264 -preset ultrafast -q:v 0 $2.mp4;
    ffmpeg -i $2.mp4 -c:v mjpeg -q:v 0 $2.avi;
}

#function parseGitBranch { git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/git:\1/'; }

if [ "$HOSTNAME" == "steffen-ubuntu" ]; then
    source /opt/ros/groovy/setup.bash
    ROS_PACKAGE_PATH=~/git/ros:$ROS_PACKAGE_PATH
    ROS_PACKAGE_PATH=~/git/care-o-bot:$ROS_PACKAGE_PATH
fi

export LD_LIBRARY_PATH=/usr/local/cuda-5.0/lib64:/lib:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda-5.0/bin:$PATH
export PATH=~/apps/bin:$PATH
export GIT_CONFIG=~/git/ubuntu_config/git/config

#export PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
cbg='\[\033[1;30m\]' #dark gray
cfg1='\[\033[0;33m\]' #yellow
cfg2='\[\033[0;32m\]' #green
cquit='\[\033[0m\]' #cancel color

#PS1="$cbg\\__($cfg1\t$cbg)__($cfg2\u$cquit@$cfg2\h$cbg)__($cfg2\w$cbg)\n \\__$(__git_ps1)\$ $cquit"
#PS1=$cbg'\\__('$cfg1'\t'$cbg')__('$cfg2'\u'$cquit'@'$cfg2'\h'$cbg')__('$cfg2'\w'$cbg')\n \\__$(__git_ps1 "(\033[0;33m%s\033[1;30m)" )'$cbg'\$ '$cquit
PS1=$cfg1'\t'$cbg'|'$cfg2'\u'$cquit'@'$cfg2'\h'$cbg'|'$cfg2'\w'$cbg'$(__git_ps1 " (\[\033[0;33m\]%s\[\033[1;30m\]) " )'$cbg'\$ '$cquit
##### Some things to install: #####
# parallel: http://www.gnu.org/software/parallel/
# Generic colorizer: http://kassiopeia.juls.savba.sk/~garabik/software/grc.html

# Printer stuff:
# list printer: lpstat -p -d
# print: lpr -P "printername" filename
# list options: lpoptions -l
# change options for user: lpoptions -o optionname=value
