#!/bin/sh

if [ "$HOSTNAME" == "steffen-ubuntu" ]; then
    alias api='sudo aptitude install'
    alias apud='sudo aptitude update'
    alias apug='sudo aptitude full-upgrade'
    alias aps='aptitude show'
    alias srm='trash-put'
    alias matlabnw='matlab -nojvm -nodisplay -nosplash'
else
    alias trash='gvfs-trash'
    alias githelper='~/git/setup/githelper'
    alias githelper-merge-def='githelper -s cob_command_tools,cob_common,cob_driver,cob_environments,cob_extern,cob_robots,cob_simulation,schunk_modular_robotics merge'
    alias ssh1='ssh cob-stud-1'
    alias ssh3='ssh cob-stud-3'
    alias ssh4='ssh cob-stud-4'
    alias ssh5='ssh cob-stud-5'
    alias ssh6='ssh cob-stud-6'
    alias ssh7='ssh cob-stud-7'
    alias ssh8='ssh cob-stud-8'
    alias ssh9='ssh cob-stud-9'
    alias cob331='ssh -X cob3-3-pc1'
    alias cob332='ssh -X cob3-3-pc2'
    alias cob333='ssh -X cob3-3-pc3'
    alias go='roscd cob_environment_perception_intern'
    alias tools='roscd cob_3d_mapping_tools'
    alias features='roscd cob_3d_mapping_features'
    alias rviz='rosrun rviz rviz'
    alias coffeetime='rosmake --pre-clean cob_environment_perception_intern'
fi

alias resource='source ~/.bashrc'
alias ..='cd ..'
alias uni='cd ~/Dropbox/Docs/Inf01'
alias em='emacs -nw'
alias gemacs='setsid emacs'

if [ "$HOSTNAME" == "steffen-ubuntu" ]; then
    alias mm='grc -c /usr/share/grc/conf.gcc -e -s make -j 4'
else
    alias mm='grc -c ~/.privat_ubuntu_config/grc/conf.gcc -e -s make -j 8'
    alias mr='grc -c ~/.privat_ubuntu_config/grc/conf.gcc -e -s rosmake --pjobs=8'
fi


alias gitk='git log --graph --decorate'
alias treel='tree -fi'
alias du='du -h --max-depth=0'

alias pdf='evince'
# tar help:
#   c: create
#   x: extract
#   f: file (in/out)
#   z: zip, dezip
alias unpack='tar xf'
alias pack='tar cfz'


# function:
findheader() { find . -type f -name '*.h' | parallel -k "grep -Hn --color=always '$@' "; }
findsource() { find . -type f -name '*.cpp' -o -name '*.hpp' | parallel -k "grep -Hn --color=always '$@' "; }
findcpp() { find . -type f -name '*.cpp' -o -name '*.hpp' -o -name '*.h' | parallel -k "grep -Hn --color=always '$@' "; }

findpy() { find . -type f -name '*.py' | parallel -k "grep -Hn --color=always '$@' "; }

masterUri() { export ROS_MASTER_URI="http://$@:11311"; }
mkcd() { mkdir $@ && cd $@; }
imgs2mjpeg()
{
    ffmpeg -f image2 -i $1 -c:v libx264 -preset ultrafast -q:v 0 $2.mp4;
    ffmpeg -i $2.mp4 -c:v mjpeg -q:v 0 $2.avi;
}

#function parseGitBranch { git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/git:\1/'; }

if [ "$HOSTNAME" == "steffen-ubuntu" ]; then
    source /opt/ros/groovy/setup.bash
    ROS_PACKAGE_PATH=~/git/ros:$ROS_PACKAGE_PATH
fi

export LD_LIBRARY_PATH=/usr/local/cuda-5.0/lib64:/lib:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda-5.0/bin:$PATH

#export PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
cbg='\[\033[1;30m\]' #dark gray
cfg1='\[\033[0;33m\]' #yellow
cfg2='\[\033[0;32m\]' #green
cquit='\[\033[0m\]' #cancel color

#PS1="$cbg\\__($cfg1\t$cbg)__($cfg2\u$cquit@$cfg2\h$cbg)__($cfg2\w$cbg)\n \\__$(__git_ps1)\$ $cquit"
#PS1=$cbg'\\__('$cfg1'\t'$cbg')__('$cfg2'\u'$cquit'@'$cfg2'\h'$cbg')__('$cfg2'\w'$cbg')\n \\__$(__git_ps1 "(\033[0;33m%s\033[1;30m)" )'$cbg'\$ '$cquit
PS1=$cbg'|'$cfg1'\t'$cbg'|'$cfg2'\u'$cquit'@'$cfg2'\h'$cbg'|'$cfg2'\w'$cbg'$(__git_ps1 " (\033[0;33m%s\033[1;30m) " )'$cbg'\$ '$cquit
##### Some things to install: #####
# parallel: http://www.gnu.org/software/parallel/
# Generic colorizer: http://kassiopeia.juls.savba.sk/~garabik/software/grc.html

