#!/bin/sh

if [ "$HOSTNAME" == "steffen-ubuntu" ]; then
    alias api='sudo aptitude install'
    alias apud='sudo aptitude update'
    alias apug='sudo aptitude full-upgrade'
    alias aps='aptitude show'
    alias srm='trash-put'
else
    alias trash='gvfs-trash'
    alias githelper='~/git/setup/githelper'
    alias githelper-merge-def='githelper -s cob_command_tools,cob_common,cob_driver,cob_environments,cob_extern,cob_robots,cob_simulation,schunk_modular_robotics merge'
    alias ssh1='ssh cob-stud-1'
    alias ssh3='ssh cob-stud-3'
    alias ssh4='ssh cob-stud-4'
    alias ssh5='ssh cob-stud-5'
    alias ssh6='ssh cob-stud-6'
    alias ssh7='ssh cob-stud-7'
    alias ssh8='ssh cob-stud-8'
    alias ssh9='ssh cob-stud-9'
    alias cob331='ssh -X cob3-3-pc1'
    alias cob332='ssh -X cob3-3-pc2'
    alias cob333='ssh -X cob3-3-pc3'
    alias go='roscd cob_environment_perception_intern'
    alias tools='roscd cob_3d_mapping_tools'
    alias features='roscd cob_3d_mapping_features'
    alias rviz='rosrun rviz rviz'
    alias coffeetime='rosmake --pre-clean cob_environment_perception_intern'
fi

alias resource='source ~/.bashrc'
alias ..='cd ..'
alias uni='cd ~/Dropbox/Docs/Inf01'
alias em='emacs -nw'
alias gemacs='setsid emacs'


alias mm='grc -c ~/.privat_ubuntu_config/grc/conf.gcc -e -s make -j 8'
alias mr='grc -c ~/.privat_ubuntu_config/grc/conf.gcc -e -s rosmake --pjobs=8'


alias gitk='git log --graph --decorate'
alias treel='tree -fi'

alias pdf='evince'
# tar help:
#   c: create
#   x: extract
#   f: file (in/out)
#   z: zip, dezip
alias unpack='tar xf'
alias pack='tar cfz'


# function:
findheader() { find . -type f -name '*.h' | parallel -k "grep -Hn --color=always '$@' "; }
findsource() { find . -type f -name '*.cpp' -o -name '*.hpp' | parallel -k "grep -Hn --color=always '$@' "; }
findcpp() { find . -type f -name '*.cpp' -o -name '*.hpp' -o -name '*.h' | parallel -k "grep -Hn --color=always '$@' "; }

findpy() { find . -type f -name '*.py' | parallel -k "grep -Hn --color=always '$@' "; }

masterUri() { export ROS_MASTER_URI="http://$@:11311"; }

if [ "$HOSTNAME" == "steffen-ubuntu" ]; then
    source /opt/ros/groovy/setup.bash
    ROS_PACKAGE_PATH=~/git/ros:$ROS_PACKAGE_PATH
fi


##### Some things to install: #####
# parallel: http://www.gnu.org/software/parallel/
# Generic colorizer: http://kassiopeia.juls.savba.sk/~garabik/software/grc.html

